### DISCUSSION TITLE
Add other device types

### DISCUSSION THREAD

**Discussion by merkens** [plamish/xcomfort#22] [Ideas]
Hello, thanks for making this integration! I have a very large xComfort installation and am using several devices not included in the current integration.

I was wondering if you are able to add other device types? The devices are known in the RPC server as the following device types.
BinaryInput
BinaryMotionSensor
HumiditySensor
LuxSensor
CurrentMeter
EnergyConsumptionMeter
PowerConsumptionMeter
VoltageMeter

Also, getting the SHC status with 'Diagnostics/getAllSystemStates' would be a nice feature if possible as it retrieves the current SHC status.

I have made a Windows application to control the SHC so I have some knowledge about the RPC server if you need more information or help regarding implementing this. I have never made an HOAS integration before so I don't know how much I can help there but would like to try if needed!

In the past I've received some documentation from Eaton regarding the RPC server. It's not complete but it helped me a lot during development. I've attached these.

[json_StatusControlFunctionRemoteInterface.pdf](https://github.com/plamish/xcomfort/files/8196553/json_StatusControlFunctionRemoteInterface.pdf)
[json_ClimateFunctionRemoteInterface.pdf](https://github.com/plamish/xcomfort/files/8196554/json_ClimateFunctionRemoteInterface.pdf)
[json-rpc.txt](https://github.com/plamish/xcomfort/files/8197693/json-rpc.txt)

**Comment by plamish** [comment]
Hey merkens,
That sounds great. Thanks for the ideas.

I need to sort out time to switch the integration from periodical calling for status to polling and improve configuration. Then we can work on adding new device types.

Adding AllSystemsStats and BinaryInput I can do with my xComfort setup. For all the rest I would need your help.

Stay tuned

**Comment by musla** [comment]
Hi @plamish, 

thanks for making the integration! I just installed HA as I am not happy with eaton SHC web and mobile application. F.ex. energy measurement is almost useless with their widgets and I got several measurement units from eaton. 

I would like also to add some more device types I am missing:
CDWA-01/3c  - contact sensor
CSAU-01/01-16IE - switching acuator, BIN input, energy measurement
CEMU-01/04 - energy measurement

Do you have any ETA about your progress? I am starting with HA and eaton. As profession I am a sw developer so I expect I could put my hands to this with little onboarding help. 

Thank you! 
Also thanks @merkens for sharing your docs.

**Reply by plamish** [reply]
Hey @musla,
The time is not my friend these days. I'm not planning, in near future, to work on extra developments beyond fixing potential issues linked with the integration incompatibility with new HA releases.

**Comment by musla** [comment]
btw, is there any other way how to control eaton units? Ie with their USB dongle plugged to Rpi4 running HA and connected to wireless network of the devices? Would that way be faster?

**Comment by merkens** [comment]
@musla you can access all devices using REST method in your Home Assistant configuration.yml. 

```
rest:
  - resource: http://SHC_IP/remote/json-rpc
    authentication: basic
    username: admin
    password: password
    method: POST
    payload: '{ "method": "StatusControlFunction/getDevices", "params": [ "hz_1", "" ], "jsonrpc": "2.0" }'
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    sensor:
      - name: "shc_kwh_meter_pc"
        unit_of_measurement: 'kWh'
        state_class: total_increasing
        device_class: energy
        json_attributes_path: "result.[?(@.id=='xCo:4753095_u0')]"
        json_attributes:
          - type
          - id
          - name
        value_template: >-
                {% for i in value_json.result %}
                {{ i.value if i.id == 'xCo:4753095_u0' }}
                {% endfor %}
```

Replace "hz_1" with the zone you want to get the data from. Use the device unique identifier (xCo:4753095_u0) to filter the results. You can add as many sensors as you want.

Also, I don't think the dongles can be used by anything except for the Eaton MRF software.
